### ISSUE TITLE
mgf error

### ISSUE THREAD

**Issue by lisujun** [spectra-cluster/spectra-cluster-cli#3]
Hi, 

I tried to ran spectra-cluster on mgf file for some testing purpose. I tested several different size of mgf, but it always has this following error:

Writing binary files...java.util.concurrent.ExecutionException: java.lang.Exception: Error while processing spectrum reference (file id = 0 > 0212_small.mgf, spec index = 3, m/z = 401.15)
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at uk.ac.ebi.pride.spectracluster.cli.BinningSpectrumConverter.waitForCompletedJobs(BinningSpectrumConverter.java:78)
        at uk.ac.ebi.pride.spectracluster.cli.BinningSpectrumConverter.processPeaklistFiles(BinningSpectrumConverter.java:56)
        at uk.ac.ebi.pride.spectracluster.cli.SpectraClusterCliMain.main(SpectraClusterCliMain.java:159)
Caused by: java.lang.Exception: Error while processing spectrum reference (file id = 0 > 0212_small.mgf, spec index = 3, m/z = 401.15)
        at uk.ac.ebi.pride.spectracluster.binning.BinarySpectrumReferenceWriter.writeSpectra(BinarySpectrumReferenceWriter.java:114)
        at uk.ac.ebi.pride.spectracluster.binning.BinarySpectrumReferenceWriterCallable.call(BinarySpectrumReferenceWriterCallable.java:33)
        at uk.ac.ebi.pride.spectracluster.binning.BinarySpectrumReferenceWriterCallable.call(BinarySpectrumReferenceWriterCallable.java:14)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at uk.ac.ebi.pride.spectracluster.util.SpectrumConverter.convertJmzReaderSpectrum(SpectrumConverter.java:33)
        at uk.ac.ebi.pride.spectracluster.binning.BinarySpectrumReferenceWriter.writeSpectra(BinarySpectrumReferenceWriter.java:87)
        ... 6 more
Error: java.lang.Exception: Error while processing spectrum reference (file id = 0 > 0212_small.mgf, spec index = 3, m/z = 401.15)

Can anyone help me on this? 

Thanks a lot. 

Best

Sujun

**Comment by jgriss** [comment]
Hi Sujun,

Thanks a lot for using the spectra-cluster-cli and reporting the issue!

Could you maybe upload / send me one of the files causing the issue? That would be a great help!

Thanks a lot!

Johannes

**Comment by lisujun** [comment]
Hi, Johannes,

 Please see the attachment zip file for the issue. 
[0212_part.zip](https://github.com/spectra-cluster/spectra-cluster-cli/files/493211/0212_part.zip)

Thanks a lot. 

Best

Sujun

**Comment by lisujun** [comment]
Hi, Johannes,

  It looks like you closed the bug. Can I clone the project to try to run on our data ?

  Thanks
Best
Sujun

**Comment by jgriss** [comment]
Hi,

If you wait about three minutes the new release will be ready for download :-)

Best,
Johannes

**Comment by jgriss** [comment]
Hi,

The release is ready now (see [version 1.0.1 release](https://github.com/spectra-cluster/spectra-cluster-cli/releases/tag/spectra-cluster-cli-1.0.1))

Best,
Johannes
