### ISSUE TITLE
Can we cluster deconvoluted top-down MS/MS mass lists?

### ISSUE THREAD

**Issue by dtabb73** [spectra-cluster/spectra-cluster-cli#9]
Hi!  I've run into a little problem trying to use spectra-cluster-cli with deconvoluted MS/MS scans.  FreeStyle Xtract is handling deconvolution of my top-down experiments, and then I am assigning precursor charges and reformatting to msAlign format (very, very similar to MGF).  When I rename my 3 msAligns to MGF and attempt to run spectra-cluster on them, I produce this error:
Converting 3 input files...
Clustering 0 binary files...
java.lang.Exception: No clustering result files found for merging.

I am unsure what format differences are causing the software to be unable to read them.  Could you look at the files in https://drive.google.com/file/d/1gvfTcx-O0zsPqTlO8MYWhXq84a9m2wBJ/view?usp=sharing to discern what is blocking the transition to binary format?

Thank you!
Dave

**Comment by jgriss** [comment]
Hi @dtabb73 ,

When you processed the files, did you keep the `.msalign` ending or did you rename the files to `.mgf`?

Unfortunately, we never added an automatic detection of file formats to the code but rely on the filename for that.

Thanks,
Johannes

**Comment by dtabb73** [comment]
Hi, Johannes.  Yes, I renamed all three files to "MGF" before running.  Specifically, my command line looked like this:
java -jar "C:\Program Files\spectra-cluster-cli-1.1.2-bin\spectra-cluster-cli-1.1.2.jar" *.mgf -output_path thing.txt

I also attempted running on a single MGF:
java -jar "C:\Program Files\spectra-cluster-cli-1.1.2-bin\spectra-cluster-cli-1.1.2.jar" -output_path thing.txt 20140722_F_EV_Hp1_repl1_Inclusion_HCD25_M_Xtract.mgf

Both result in this error:
Clustering 0 binary files...
java.lang.Exception: No clustering result files found for merging.
        at uk.ac.ebi.pride.spectracluster.implementation.SpectraClusterStandalone.mergeClusteringResults(SpectraClusterStandalone.java:584)
        at uk.ac.ebi.pride.spectracluster.implementation.SpectraClusterStandalone.clusterBinaryFiles(SpectraClusterStandalone.java:122)
        at uk.ac.ebi.pride.spectracluster.implementation.SpectraClusterStandalone.clusterPeaklistFiles(SpectraClusterStandalone.java:103)
        at uk.ac.ebi.pride.spectracluster.cli.SpectraClusterCliMain.run(SpectraClusterCliMain.java:344)
        at uk.ac.ebi.pride.spectracluster.cli.SpectraClusterCliMain.main(SpectraClusterCliMain.java:43)
Error: No clustering result files found for merging.

Thanks!
DT
